version: "2.0"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
  api:
    image: segovchik/api:latest
    depends_on:
      - db
    ports:
      - "4000:4000"


